apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: <namespace_deployment_is_present>
spec:
 type: NodePort
 ports:
  - port: 80 # port of the service which it communicates to pod
    targetPort: 8080 # port of the pod which service communicates to 
    nodePort: 30000 # one of the available port on the node.
 selector:
  name: myapp-deployment # select one of the label of the deployment
  